import mlx.core as mx

def have_fenv() -> bool: ...
def random_double(size: int, rng: mx.random.RandomState) -> mx.float64: ...
def test_add_round(size: int, mode: str, rng: mx.random.RandomState): ...

def _dd_exp(xhi: float, xlo: float) -> tuple[float, float]: ...
def _dd_log(xhi: float, xlo: float) -> tuple[float, float]: ...
def _dd_expm1(xhi: float, xlo: float) -> tuple[float, float]: ...
